name: Deploy Flask App to GitHub Pages

on:
  push:
    branches:
      - main

env:
  HEALTHCHECK_URL: http://34.228.255.233:50000

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.12]
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
 
    # 建立環境
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
 
    # 運行測試
    - name: Run Tests
      run: |
        python -m flask run